/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.controlUI;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import gnu.io.CommPortIdentifier; 
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent; 
import gnu.io.SerialPortEventListener; 
import java.awt.Color;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author sherry
 */
public class ControlUI extends javax.swing.JFrame implements SerialPortEventListener{

    boolean auto=true;
    SerialPort serialPort;
    private static final String PORT_NAMES[] = { 
			"/dev/tty.usbserial-A9007UX1", // Mac OS X
			"COM3", // Windows
    };
    //<editor-fold defaultstate="collapsed" desc="SerialPort Var">
    /**
	* A BufferedReader which will be fed by a InputStreamReader 
	* converting the bytes into characters 
	* making the displayed results codepage independent
	*/
	private BufferedReader input;
	/** The output stream to the port */
	private OutputStream output;
	/** Milliseconds to block while waiting for port open */
	private static final int TIME_OUT = 2000;
	/** Default bits per second for COM port. */
	private static final int DATA_RATE = 9600;
    //</editor-fold>
        
    public void initialize(){
        CommPortIdentifier portId = null;
        Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();
        
        //First, Find an instance of serial port as set in PORT_NAMES.
        while (portEnum.hasMoreElements()) {
            CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
            for (String portName : PORT_NAMES) {
                if (currPortId.getName().equals(portName)) {
                    portId = currPortId;
                    break;
		}
            }
	}
	if (portId == null) {
            System.out.println("Could not find COM port.");
            return;
	}
        
        try {
            // open serial port, and use class name for the appName.
            serialPort = (SerialPort) portId.open(this.getClass().getName(),
			TIME_OUT);

            // set port parameters
            serialPort.setSerialPortParams(DATA_RATE,
                                SerialPort.DATABITS_8,
                                SerialPort.STOPBITS_1,
                                SerialPort.PARITY_NONE);

            // open the streams
            input = new BufferedReader(new InputStreamReader(serialPort.getInputStream()));
            output = serialPort.getOutputStream();

            // add event listeners
            serialPort.addEventListener(this);
            serialPort.notifyOnDataAvailable(true);
	} catch (Exception e) {
            System.err.println(e.toString());
        }
    }
    
    /**
	 * This should be called when you stop using the port.
	 * This will prevent port locking on platforms like Linux.
	 */
    public synchronized void close(){
        if(serialPort!=null){
            serialPort.removeEventListener();
            serialPort.close();
        }
    }
    
    /**
	 * Handle an event on the serial port. Read the data and print it.
	 */
    @Override
    public synchronized void serialEvent(SerialPortEvent oEvent) {
	if (oEvent.getEventType() == SerialPortEvent.DATA_AVAILABLE) {
            try {
		String inputLine=input.readLine();
		System.out.println(inputLine);
                this.photo1.setText(inputLine);
            } catch (Exception e) {
		System.err.println(e.toString());
            }
	}
	// Ignore all the other eventTypes, but you should consider the other ones.
    }
    
    /**
     * Creates new form ControlUI
     */
    public ControlUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Set_Temp = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        setTempField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        setTempButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ControlPanel = new javax.swing.JPanel();
        TempPanel = new javax.swing.JPanel();
        InTempLable = new javax.swing.JLabel();
        OutTempLable = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        SetTempLable = new javax.swing.JLabel();
        setTemp_show = new javax.swing.JTextField();
        ChangeSetTemp = new javax.swing.JButton();
        EnegerPanel = new javax.swing.JPanel();
        user_pre_mode_ind = new javax.swing.JLabel();
        energy_save_ind = new javax.swing.JLabel();
        mannual_mode_ind = new javax.swing.JLabel();
        SettingPanel = new javax.swing.JPanel();
        Slider = new javax.swing.JSlider();
        jTextField3 = new javax.swing.JTextField();
        SetButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        photo1 = new javax.swing.JTextField();
        mode = new javax.swing.JToggleButton();
        energy_save_en = new javax.swing.JToggleButton();
        HelpPanel = new javax.swing.JPanel();
        AboutPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        Set_Temp.setTitle("Set Room Temperature");
        Set_Temp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Set_Temp.setMinimumSize(new java.awt.Dimension(427, 180));
        Set_Temp.setType(java.awt.Window.Type.POPUP);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Set Room Temperature to:");

        setTempField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setTempField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        setTempField.setText("24");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("℃");

        setTempButton.setText("Confirm");
        setTempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTempButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Set_TempLayout = new javax.swing.GroupLayout(Set_Temp.getContentPane());
        Set_Temp.getContentPane().setLayout(Set_TempLayout);
        Set_TempLayout.setHorizontalGroup(
            Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Set_TempLayout.createSequentialGroup()
                .addGroup(Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Set_TempLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(setTempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addGroup(Set_TempLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setTempField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        Set_TempLayout.setVerticalGroup(
            Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Set_TempLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Set_TempLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setTempField)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Set_TempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setTempButton)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        TempPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TempPanel.setPreferredSize(new java.awt.Dimension(280, 191));

        InTempLable.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        InTempLable.setText("Room Temp(℃)");

        OutTempLable.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        OutTempLable.setText("Outside Temp(℃)");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTextField1.setText("0");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jTextField2.setText("10");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        SetTempLable.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        SetTempLable.setText("Set Temp(℃)");

        setTemp_show.setEditable(false);
        setTemp_show.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        setTemp_show.setText("0");

        ChangeSetTemp.setText("Change");
        ChangeSetTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSetTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TempPanelLayout = new javax.swing.GroupLayout(TempPanel);
        TempPanel.setLayout(TempPanelLayout);
        TempPanelLayout.setHorizontalGroup(
            TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TempPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutTempLable)
                    .addComponent(InTempLable, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetTempLable, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setTemp_show, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TempPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangeSetTemp)
                .addContainerGap())
        );
        TempPanelLayout.setVerticalGroup(
            TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TempPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutTempLable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2))
                .addGap(18, 18, 18)
                .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InTempLable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetTempLable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setTemp_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangeSetTemp)
                .addGap(24, 24, 24))
        );

        EnegerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EnegerPanel.setPreferredSize(new java.awt.Dimension(280, 191));

        user_pre_mode_ind.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        user_pre_mode_ind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_pre_mode_ind.setText("User Preference Mode");

        energy_save_ind.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        energy_save_ind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        energy_save_ind.setText("Energy Saving Mode");

        mannual_mode_ind.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        mannual_mode_ind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mannual_mode_ind.setText("Manual Mode");

        javax.swing.GroupLayout EnegerPanelLayout = new javax.swing.GroupLayout(EnegerPanel);
        EnegerPanel.setLayout(EnegerPanelLayout);
        EnegerPanelLayout.setHorizontalGroup(
            EnegerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnegerPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(EnegerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_pre_mode_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(energy_save_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EnegerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EnegerPanelLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(mannual_mode_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(32, 32, 32)))
        );
        EnegerPanelLayout.setVerticalGroup(
            EnegerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnegerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(energy_save_ind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user_pre_mode_ind, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(EnegerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EnegerPanelLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(mannual_mode_ind, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        Slider.setMaximum(90);
        Slider.setMinimum(-90);
        Slider.setValue(0);
        Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Slider, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SetButton.setText("Set");
        SetButton.setMaximumSize(new java.awt.Dimension(63, 23));
        SetButton.setMinimumSize(new java.awt.Dimension(63, 23));
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Degree");

        jLabel4.setText("Up//");

        jLabel5.setText("Down\\\\");

            jLabel6.setText("light:");

            photo1.setEditable(false);

            mode.setText("Auto Mode");
            mode.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    modeMouseClicked(evt);
                }
            });
            mode.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    modeActionPerformed(evt);
                }
            });

            energy_save_en.setText("Energy Saving Mode");
            energy_save_en.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    energy_save_enMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout SettingPanelLayout = new javax.swing.GroupLayout(SettingPanel);
            SettingPanel.setLayout(SettingPanelLayout);
            SettingPanelLayout.setHorizontalGroup(
                SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SettingPanelLayout.createSequentialGroup()
                    .addGap(319, 319, 319)
                    .addComponent(SetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(209, 209, 209))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(SettingPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addGap(116, 116, 116))
                .addGroup(SettingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(photo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(152, 152, 152)
                    .addComponent(mode)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(energy_save_en)
                    .addContainerGap())
            );
            SettingPanelLayout.setVerticalGroup(
                SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingPanelLayout.createSequentialGroup()
                    .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SettingPanelLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mode)
                                .addComponent(photo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGroup(SettingPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(energy_save_en)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                    .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3)
                            .addComponent(jLabel3))
                        .addComponent(Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(SetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20))
            );

            javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
            ControlPanel.setLayout(ControlPanelLayout);
            ControlPanelLayout.setHorizontalGroup(
                ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ControlPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlPanelLayout.createSequentialGroup()
                            .addComponent(SettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(ControlPanelLayout.createSequentialGroup()
                            .addComponent(TempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EnegerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            ControlPanelLayout.setVerticalGroup(
                ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ControlPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TempPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(EnegerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Control", ControlPanel);

            javax.swing.GroupLayout HelpPanelLayout = new javax.swing.GroupLayout(HelpPanel);
            HelpPanel.setLayout(HelpPanelLayout);
            HelpPanelLayout.setHorizontalGroup(
                HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 599, Short.MAX_VALUE)
            );
            HelpPanelLayout.setVerticalGroup(
                HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 423, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Help", HelpPanel);

            AboutPanel.setBackground(new java.awt.Color(255, 255, 255));

            jTextArea1.setEditable(false);
            jTextArea1.setColumns(20);
            jTextArea1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
            jTextArea1.setRows(5);
            jTextArea1.setText("Group No. 15 \nSmart Retrofit Device To Improve Thermal Control Through Shutter Blinds\n\nMario Nahed, B. Mech Eng, SMP No.051452\nAlbert Ngo, B. Mech Eng, SMP No.055166\nXiangyu Ruan, B. Comp Eng, SMP No.055336\nAndrew Nguyen, B. Mech Eng, SMP No.055167\n\nFaculty advisor:Wael H. Ahmed Ph.D., P.Eng.\n");
            jTextArea1.setBorder(null);
            jScrollPane1.setViewportView(jTextArea1);

            javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
            AboutPanel.setLayout(AboutPanelLayout);
            AboutPanelLayout.setHorizontalGroup(
                AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AboutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addContainerGap())
            );
            AboutPanelLayout.setVerticalGroup(
                AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AboutPanelLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("About", AboutPanel);

            jLabel2.setText("Version 1.0");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
            );

            bindingGroup.bind();

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
        try {
            int value = this.Slider.getValue();
            String outString = "A" + value;
            if(auto){
                auto=false;
                output.write(outString.getBytes());
                this.photo1.setText("第一次");                
            }else{
                output.write(200);
                output.write(outString.getBytes());
                this.photo1.setText("第二次");  
            }
        } catch (IOException e1) {
            e1.printStackTrace();
	}
    }//GEN-LAST:event_SetButtonActionPerformed

    private void modeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeMouseClicked
        if(this.mode.isSelected()){                      //auto mode
            auto = true;
            this.SetButton.setEnabled(false); 
            try {
                output.write("A200".getBytes());
            } catch (IOException ex) {
                Logger.getLogger(ControlUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.mannual_mode_ind.setBackground(Color.white);
            this.user_pre_mode_ind.setBackground(Color.green);
        }else{                                           //manual mode     
            this.SetButton.setEnabled(true);
            this.mannual_mode_ind.setBackground(Color.green);
            this.user_pre_mode_ind.setBackground(Color.white);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_modeMouseClicked

    private void ChangeSetTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSetTempActionPerformed
        Set_Temp.setVisible(true);
    }//GEN-LAST:event_ChangeSetTempActionPerformed

    private void setTempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTempButtonActionPerformed
        
        String setTemp_toString = "S" + this.setTempField.getText();
        try {
            this.setTemp_show.setText(this.setTempField.getText());
            output.write(setTemp_toString.getBytes());
            this.Set_Temp.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ControlUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setTempButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Set_Temp.dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeActionPerformed

    private void energy_save_enMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_energy_save_enMouseClicked
        // TODO add your handling code here:
        if(this.energy_save_en.isSelected()){                      //auto mode
            auto = true;
            this.SetButton.setEnabled(false); 
            this.mode.setEnabled(false);
            try {
                output.write("E100".getBytes());
            } catch (IOException ex) {
                Logger.getLogger(ControlUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.energy_save_ind.setBackground(Color.green);
            this.mannual_mode_ind.setBackground(Color.white);
            this.user_pre_mode_ind.setBackground(Color.white);
        }else{                                           //manual mode     
            this.SetButton.setEnabled(true);
             try {
                output.write("E200".getBytes());
            } catch (IOException ex) {
                Logger.getLogger(ControlUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.mannual_mode_ind.setBackground(Color.white);
            this.user_pre_mode_ind.setBackground(Color.white);
        }  
    }//GEN-LAST:event_energy_save_enMouseClicked

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String[] args) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ControlUI main = new ControlUI();
                main.setVisible(true);
                main.initialize();
            }
        });
        //<editor-fold defaultstate="collapsed" desc="SerialTest">
	Thread t=new Thread() {
            public void run() {
		//the following line will keep this app alive for 1000 seconds,
		//waiting for events to occur and responding to them (printing incoming messages to console).
		try {Thread.sleep(1000000);} catch (InterruptedException ie) {}
            }
	};
	t.start();
	System.out.println("Started");  
        //</editor-fold>
    }
    
    public void setPhoto1(String value){
        photo1.setText(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JButton ChangeSetTemp;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel EnegerPanel;
    private javax.swing.JPanel HelpPanel;
    private javax.swing.JLabel InTempLable;
    private javax.swing.JLabel OutTempLable;
    private javax.swing.JButton SetButton;
    private javax.swing.JLabel SetTempLable;
    private javax.swing.JFrame Set_Temp;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JSlider Slider;
    private javax.swing.JPanel TempPanel;
    private javax.swing.JToggleButton energy_save_en;
    private javax.swing.JLabel energy_save_ind;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel mannual_mode_ind;
    private javax.swing.JToggleButton mode;
    private javax.swing.JTextField photo1;
    private javax.swing.JButton setTempButton;
    private javax.swing.JTextField setTempField;
    private javax.swing.JTextField setTemp_show;
    private javax.swing.JLabel user_pre_mode_ind;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
